
future_window: 2
past_window: 28
batch_size: 256
max_epochs: 40
min_epochs: 30

model:
  name: Informer
  d_model: 256
  d_fully_connected: 256
  n_attention_heads: 2
  dropout: 0.01
  n_encoder_layers: 1
  n_decoder_layers: 3
  learning_rate: 0.001
  optimizer: 'Adam'

data:
  path: /teamspace/studios/this_studio/informer-validation/data/btc_features_5min.csv
  target: target
  time_index: time_index
  group_ids: group_ids
  static_real: []
  static_cat: []
  dynamic_known_real: ['fear_and_greed', 'vix', 'fed_rates', 'fed_rates', 'vol_1d', 'vol_7d']
  dynamic_known_cat: ['weekday', 'hour']
  dynamic_unknown_real: [
    'open', 'high', 'low', 'close', 'volume', 'returns', 'open_to_close', 'high_to_close', 
    'low_to_close', 'vol_1h', 'sma_1h', 'sma_1d', 'sma_7d', 'ema_1h', 'ema_1d', 'ema_7d', 'macd', 'macd_signal', 
    'rsi', 'bb_mid', 'bb_up', 'bb_low'
  ]
  dynamic_unknown_cat: []

loss:
  name: GMADL
  a: 1000.0
  b: 2.0


experiment:
  name: Informer_BTC_5min
  log_dir: /teamspace/studios/this_studio/informer-validation/logs
  save_model: true
  early_stopping_patience: 10
  validation_interval: 1
  log_interval: 10
  seed: 42