
future_window: 2
past_window: 28
batch_size: 256
max_epochs: 40

model:
  name: Informer
  d_model: 256
  d_fully_connected: 256
  n_attention_heads: 2
  dropout: 0.01
  n_encoder_layers: 1
  n_decoder_layers: 3
  learning_rate: 0.001
  optimizer: "Adam"

data:
  path: /Users/apple/Desktop/time-series/informer-validation/data/btc_features_5min.csv
  target: target
  time_index: time_index
  group_ids: group_ids
  static_real: []
  static_cat: []
  dynamic_known_real: []
  dynamic_known_cat: ['weekday', 'hour']
  dynamic_unknown_real: [
    'open', 'high', 'low', 'close', 'volume', 'returns', 'fear_and_greed', 'vix', 'fed_rates', 'open_to_close', 'high_to_close', 
    'low_to_close', 'vol_1h', 'vol_1d', 'vol_7d', 'sma_1h', 'sma_1d', 'sma_7d', 'ema_1h', 'ema_1d', 'ema_7d', 'macd', 'macd_signal', 
    'rsi', 'bb_mid', 'bb_up', 'bb_low'
  ]
  dynamic_unknown_cat: []

loss:
  name: GMADL
  a: 1000.0
  b: 2.0